# Generated by Django 5.2.1 on 2025-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerecord',
            name='total_to_pay',
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='total_charge',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
